var VimeoState={UNSTARTED:-1,ENDED:0,PLAYING:1,PAUSED:2,BUFFERING:3};
vjs.Vimeo=function(a,d,e){vjs.MediaTechController.call(this,a,d,e);if(a=d.source.src.match(/^.*(vimeo\.com\/)((channels\/[A-z]+\/)|(groups\/[A-z]+\/videos\/))?([0-9]+)/))this.videoId=a[5];this.id_=this.player_.id()+"_vimeo_api";a={api:1,byline:0,portrait:0,show_title:0,show_byline:0,show_portait:0,fullscreen:1,player_id:this.id(),autoplay:this.player_.options_.autoplay?1:0,loop:this.player_.options_.loop?1:0};this.baseUrl="https"==document.location.protocol?"https://secure.vimeo.com/video/":"http://player.vimeo.com/video/";
this.vimeo={};this.vimeoInfo={};this.el_.vjsTech=this;this.el_.onload=function(){this.vjsTech.onLoad()};this.el_.src=this.baseUrl+this.videoId+"?"+vjs.Vimeo.makeQueryString(a)};goog.inherits(vjs.Vimeo,vjs.MediaTechController);vjs.Vimeo.prototype.dispose=function(){vjs.Vimeo.superClass_.dispose.call(this);this.vimeo.api("unload");delete this.vimeo;this.el_.parentNode.removeChild(this.el_)};
vjs.Vimeo.prototype.createEl=function(){var a=this.player_,d=vjs.createEl("iframe",{id:a.id()+"_vimeo_api",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0,webkitAllowFullScreen:"",mozallowfullscreen:"",allowFullScreen:""});vjs.insertFirst(d,a.el());return d};
vjs.Vimeo.prototype.onLoad=function(){this.vimeo=$f(this.el_);this.vimeoInfo={state:VimeoState.UNSTARTED,volume:1,muted:!1,muteVolume:1,time:0,duration:0,buffered:0,url:this.baseUrl+this.videoId,error:null};this.vimeo.addEvent("ready",function(a){vjs.el(a).vjsTech.onReady()});this.vimeo.addEvent("loadProgress",function(a,d){vjs.el(d).vjsTech.onLoadProgress(a)});this.vimeo.addEvent("playProgress",function(a,d){vjs.el(d).vjsTech.onPlayProgress(a)});this.vimeo.addEvent("play",function(a){vjs.el(a).vjsTech.onPlay()});
this.vimeo.addEvent("pause",function(a){vjs.el(a).vjsTech.onPause()});this.vimeo.addEvent("finish",function(a){vjs.el(a).vjsTech.onFinish()});this.vimeo.addEvent("seek",function(a){vjs.el(a).vjsTech.onSeek(data)})};vjs.Vimeo.prototype.play=function(){this.vimeo.api("play")};vjs.Vimeo.prototype.pause=function(){this.vimeo.api("pause")};vjs.Vimeo.prototype.paused=function(){return this.lastState!==VimeoState.PLAYING&&this.lastState!==VimeoState.BUFFERING};
vjs.Vimeo.prototype.currentTime=function(){return this.vimeoInfo.time||0};vjs.Vimeo.prototype.setCurrentTime=function(a){this.vimeo.api("seekTo",a);this.player_.trigger("timeupdate")};vjs.Vimeo.prototype.duration=function(){return this.vimeoInfo.duration||0};vjs.Vimeo.prototype.buffered=function(){return vjs.createTimeRange(0,this.vimeoInfo.buffered||0)};vjs.Vimeo.prototype.volume=function(){return this.vimeoInfo.muted?this.vimeoInfo.muteVolume:this.vimeoInfo.volume};
vjs.Vimeo.prototype.setVolume=function(a){this.vimeo.api("setvolume",a);this.vimeo.vimeoInfo.volume=a;this.player_.trigger("volumechange")};vjs.Vimeo.prototype.muted=function(){return this.vimeoInfo.muted||!1};vjs.Vimeo.prototype.setMuted=function(a){a?(this.vimeoInfo.muteVolume=this.vimeoInfo.volume,this.setVolume(0)):this.setVolume(this.vimeoInfo.muteVolume);this.vimeoInfo.muted=a;this.player_.trigger("volumechange")};
vjs.Vimeo.prototype.onReady=function(){this.triggerReady();this.player_.trigger("canplay");this.player_.bigPlayButton.hide();this.player_.posterImage.hide();this.player_.controlBar.hide()};vjs.Vimeo.prototype.onLoadProgress=function(a){var d=!this.vimeoInfo.duration;this.vimeoInfo.duration=a.duration;this.vimeoInfo.buffered=a.percent;this.player_.trigger("progress");d&&this.player_.trigger("durationchange")};vjs.Vimeo.prototype.onPlayProgress=function(a){this.vimeoInfo.time=a.seconds;this.player_.trigger("timeupdate")};
vjs.Vimeo.prototype.onPlay=function(){this.vimeoInfo.state=VimeoState.PLAYING;this.player_.trigger("play")};vjs.Vimeo.prototype.onPause=function(){this.vimeoInfo.state=VimeoState.PAUSED;this.player_.trigger("pause")};vjs.Vimeo.prototype.onFinish=function(){this.vimeoInfo.state=VimeoState.ENDED;this.player_.trigger("ended")};vjs.Vimeo.prototype.onSeek=function(a){this.vimeoInfo.time=a.seconds;this.player_.trigger("timeupdate");this.player_.trigger("seeked")};vjs.Vimeo.isSupported=function(){return!0};
vjs.Vimeo.canPlaySource=function(a){return"video/vimeo"==a.type};vjs.Vimeo.prototype.features={fullscreen:!0,volumeControl:!0};vjs.Vimeo.makeQueryString=function(a){var d=[],e;for(e in a)a.hasOwnProperty(e)&&d.push(encodeURIComponent(e)+"="+encodeURIComponent(a[e]));return d.join("&")};
var Froogaloop=function(){function a(l){return new a.fn.init(l)}function d(a,c,b){if(!b.contentWindow.postMessage)return!1;var d=b.getAttribute("src").split("?")[0];a=JSON.stringify({method:a,value:c});"//"===d.substr(0,2)&&(d=window.location.protocol+d);b.contentWindow.postMessage(a,d)}function e(a){var c,b;try{c=JSON.parse(a.data),b=c.event||c.method}catch(d){}"ready"==b&&!h&&(h=!0);if(a.origin!=j)return!1;a=c.value;var e=c.data,g=""===g?null:c.player_id;c=g?f[g][b]:f[b];b=[];if(!c)return!1;void 0!==
a&&b.push(a);e&&b.push(e);g&&b.push(g);return 0<b.length?c.apply(null,b):c.call()}function k(a,c,b){b?(f[b]||(f[b]={}),f[b][a]=c):f[a]=c}var f={},h=!1,j="";a.fn=a.prototype={element:null,init:function(a){"string"===typeof a&&(a=document.getElementById(a));this.element=a;a=this.element.getAttribute("src");"//"===a.substr(0,2)&&(a=window.location.protocol+a);a=a.split("/");for(var c="",b=0,d=a.length;b<d;b++){if(3>b)c+=a[b];else break;2>b&&(c+="/")}j=c;return this},api:function(a,c){if(!this.element||
!a)return!1;var b=this.element,e=""!==b.id?b.id:null,f=!c||!c.constructor||!c.call||!c.apply?c:null,g=c&&c.constructor&&c.call&&c.apply?c:null;g&&k(a,g,e);d(a,f,b);return this},addEvent:function(a,c){if(!this.element)return!1;var b=this.element,e=""!==b.id?b.id:null;k(a,c,e);"ready"!=a?d("addEventListener",a,b):"ready"==a&&h&&c.call(null,e);return this},removeEvent:function(a){if(!this.element)return!1;var c=this.element,b=""!==c.id?c.id:null;a:{if(b&&f[b]){if(!f[b][a]){b=!1;break a}f[b][a]=null}else{if(!f[a]){b=
!1;break a}f[a]=null}b=!0}"ready"!=a&&b&&d("removeEventListener",a,c)}};a.fn.init.prototype=a.fn;window.addEventListener?window.addEventListener("message",e,!1):window.attachEvent("onmessage",e);return window.Froogaloop=window.$f=a}();